AWS_ACCESS_KEY_ID = 'AKIAIGIONPLVCNED37TQ'
AWS_SECRET_ACCESS_KEY = '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'

# 4 instance, equnix directconnect
#AWS_ACCESS_KEY_ID = 'AKIAJXEYWXBZMBGUV2PQ'
#AWS_SECRET_ACCESS_KEY = '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'
